import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import ClientProvider from "../provider/ClientProvider";
import ThemeProvider from "@/provider/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider>
          <ThemeProvider>
            <header className="sticky top-0 z-100">
              <Navbar />
            </header>

            <main>{children}</main>

            <footer>
              <Footer />
            </footer>
          </ThemeProvider>
        </ClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
