import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import ClientProvider from "../provider/ClientProvider";
import Script from "next/script";
import GlobalBackground from "@/components/shared/GlobalBackground";
import ThemeProvider from "@/provider/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider>
          <ThemeProvider>
            <header className="sticky top-0 z-100">
              <Navbar />
            </header>
            <GlobalBackground />

            <main className="relative z-10">{children}</main>

            <footer>
              <Footer />
            </footer>
            <Script
              src="https://upload-widget.cloudinary.com/global/all.js"
              strategy="beforeInteractive"
            />
          </ThemeProvider>
        </ClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
